export const Mutations = {
  SET_FROM_VALUE: "SET_FROM_VALUE",
  SET_TO_VALUE: "SET_TO_VALUE",
  SET_FROM_CURRENCY: "SET_FROM_CURRENCY",
  SET_TO_CURRENCY: "SET_TO_CURRENCY",
  SET_PRICE: "SET_PRICE",
  SET_HISTORY: "SET_HISTORY",
  SET_LAST_DAYS: "SET_LAST_DAYS",
  SET_TIME_RANGE: "SET_TIME_RANGE",
};

export const Actions = {
  SET_VALUE: "SET_VALUE",
  SET_CURRENCY: "SET_CURRENCY",
  SET_TIME_RANGE: "SET_TIME_RANGE",
  UPDATE_PRICE: "UPDATE_PRICE",
  UPDATE_HISTORY: "UPDATE_HISTORY",
  UPDATE_LAST_DAYS: "UPDATE_LAST_DAYS",
};
